apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "e2e-${APPLICATION}-${ENVIRONMENT}"
labels:
  - pairs:
      app.kubernetes.io/name: "${APPLICATION}"
      app.kubernetes.io/instance: "${ENVIRONMENT}"
      app.kubernetes.io/component: common
      app.kubernetes.io/version: "${COMMIT_SHA}"
    fields:
      - group: ""
        version: v1
        kind: Namespace
        path: metadata/labels
        create: true
resources:
  - namespace.yaml
